sudo: required

services:
  - docker

before_install:
  - docker build -t vadimgore/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vadimgore/react-test npm test -- --coverage

after_success:
  - docker build -t vadimgore/multi-client ./client
  - docker build -t vadimgore/multi-nginx ./nginx
  - docker build -t vadimgore/multi-server ./server
  - docker build -t vadimgore/multi-worker ./worker
  #Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Push these images to docker hub
  - docker push vadimgore/multi-client
  - docker push vadimgore/multi-nginx
  - docker push vadimgore/multi-server
  - docker push vadimgore/multi-worker

